build:
    environment:
        mysql: false
        redis: false
        php:
            version: 5.6

tools:
    external_code_coverage: true
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_mess_detector: true
    php_pdepend: true
    php_sim: true

filter:
    excluded_paths:
        - tests/*
        - sample/*
